### ISSUE TITLE
Analytics for Spatial 

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#200]
### Context

We're adding spatial modality. We should also track some stats for future product decisions 

### Problem or idea

Track:
- Do people download both spatial and sc data in the same session?
- What is the ratio of people getting only one of them vs both?

**Comment by davidsmejia** [comment]
after #201

**Comment by nozomione** [comment]
> Do people download both spatial and sc data in the same session?

This will already be accounted for, because we currently track the computed file type.
That will either be:
``'PROJECT_ZIP', 'SAMPLE_ZIP', 'PROJECT_SPATIAL_ZIP', 'SAMPLE_SPATIAL_ZIP'
``

> What is the ratio of people getting only one of them vs both?

We currently has no concept of tracking a user outside of what GA does. There is a way to do so, but it would still require for us to generate a custom report for it in order to get that information(according to David).

**Comment by davidsmejia** [comment]
Closing with opened admin issue.
