### ISSUE TITLE
Link to matched text in Markdown Page

### ISSUE THREAD

**Issue by davidsmejia** [AlexsLemonade/scpca-portal#531]
### Context

We want to be able to link people to specific parts of the Terms page.

The current `MarkDownPage` is great for maintaining documentation from legal to serve on the site. One limitation we currently have is that if we change the Markdown, there is no way to keep that consistent with the original docx file.

### Problem or idea

We should add logic to the `MarkdownPage` that allows us to navigate to any page that uses that component and read a query parameter called `match`. The value of this query parameter should be a string that should match the inner text of an element on the page.

Ex: `/terms-of-use?match=Access to and Use of Content` should load the page and then scroll down until that section is at the top of the screen.

These markdown docs change infrequently but do change. In order to prevent this from breaking in the future we should collect the strings that we want to match in a config file that we can write tests for in a future issue. For now, lets just have `Access to and Use of Content` in there as we will be using that soon.

A suggestion for solving this would be using XPath.

### Solution or next step

- add new config for matchable sections of the about page
- add mentioned logic to `MarkdownPage`

**Comment by nozomione** [comment]
@davidsmejia Instead of using a query parameter `match`, do you want to generate a navigation (a kind of table of contents) and display it at the top of a page, making it easier for users to navigate through each section (or both)?

**Comment by davidsmejia** [comment]
Hey I think I understand what you mean, could you just give me an initial approach to how we would have the auto-inserted ids?

I think the TOC/menu features are outside of the scope of what we are trying to accomplish at this moment. Could you create a new issue for that and then ping me and Deepa for that. I don't have any reason to say we shouldn't do it at this time just that there would be some design to it and we don't explicitly need it at this time.

**Comment by nozomione** [comment]
> an initial approach to how we would have the auto-inserted ids?

My approach is to first get all the necessary DOM elements of the sections that need be linkable in a markdown page (e.g., `Eligibility`, `Account Registration `, `Access to and Use of Content`), and then assign an `id` to each section so that it can be linked from anywhere in the application. 

> I think the TOC/menu features are outside of the scope of what we are trying to accomplish at this moment. Could you create a new issue for that and then ping me and Deepa for that.

Sure, will do 👍 I was going to ask Deepa's feedback if one of my suggestions above would be a good candidate for a new feature to be added to markdown pages (and if so, yes, that would be handled in a separate issue!).

**Comment by davidsmejia** [comment]
> My approach is to first get all the necessary DOM elements of the sections that need be linkable in a markdown page (e.g., Eligibility, Account Registration , Access to and Use of Content), and then assign an id to each section so that it can be linked from anywhere in the application.

What I like about your suggestion is that it looks and feels like how you would normally link to a div or element on a page. Ideally we would be able to implement this outside of editing the markdown which is what I think you mean when you say auto inserted id's.

One thing that I think might be useful with using something like XPath or more generally searching innertext is that it would allow us to navigate nested subsections without assigning id's on the server by default since it doesn't care about the page structure only the contents and would work on any `MarkdownPage` component. 

So in the future if we need to add new predefined sections that we want to link to, we would just add them to the config and use them and the matcher would already be able to find the element that contains the text.

Additionally, we would be able to write tests since the `.md` file would have to be checked on update we could automate a test to ensure that anything we explicitly want to match can be found in the markdown file as a check via github actions.

So I think the inner text solution would be a quick implementation that would be more flexible for the future usage since we are dealing with a document that we really don't want to make modifications whenever we want to update it. I think either solution would be testable.

If you want to implement the assigning id's for now that seems ok to me since we don't really have any actual use cases for this at the moment other than linking to `Access to and Use of Content` in an upcoming issue.

**Comment by nozomione** [comment]
Yes, let's use the `id` for page linking on FE.

> Ideally we would be able to implement this outside of editing the markdown which is what I think you mean when you say auto inserted id's.

As chatted on 1:1, inserting an `id` to each section won’t edit the original markdown, since that manipulation will be performed on html elements that we generate using that markdown file and those `id` attributes will be only present during runtime (when component mounts and renders the page in a browser). 

Here is the approach using the `id. Please let me know if any suggestions/ideas: 

On FE, at runtime, we'll use the most recent markdown file to populate a list of linkable sections, and it will be re-populated when changes are made to the markdown file and is committed to CVS.

#### Breakdown:

**Step 1:** After the `MarkdownPage` component is mounted (when the markdown HTML is ready),  we get all the sections that needs to be linked. HTML for `Terms of Use` and `Privacy Policy` currently share the same page structure, so those sections can be easy to be obtained.

**Step 2:** Once you have a list of all the sections that can be linked, insert IDs into them using text contents (e.g., `Eligibility`, `Account Registration`, `Access to and Use of Content`).

>  ...we need to add new predefined sections that we want to link to, we would just add them to the config  and use them and the matcher would already be able to find the element that contains the text.

**Step 3:** For the config, we can create it using that text contents (in **Step 2**)  

**Step 4:** We'll create a macther helper (e.g., `getMarkdownLink(route, section)`) which composes a URL for each section based on the given page route and section name (defined in the config), so that it can be used anywhere in the application.

#### Current status: 

Currently, I'm having some struggles with the site's structure. I was able to link each section, however when scrolled (to that section on page load), the site header and the content of the selected section's content overlap. 

I am trying to hack it but the site structure might need to be adjusted. Let me know your thought on this (any alternative solution)!

e.g. ) the terms of use page
The linked sections:
![Screenshot 2024-02-01 at 7 20 12 PM](https://github.com/AlexsLemonade/scpca-portal/assets/31800566/291a47b2-2c6e-4821-86d7-027370ffc5be)

The selected section's content overlaps with the site header (*disregard the border, it's for testing):
![Screenshot 2024-02-01 at 7 21 50 PM](https://github.com/AlexsLemonade/scpca-portal/assets/31800566/47b2ab22-2b48-4d67-b165-479f24aa4df2)

But it should be: 
![Screenshot 2024-02-01 at 7 24 03 PM](https://github.com/AlexsLemonade/scpca-portal/assets/31800566/e53a6e22-d861-4f3c-8b80-8deba4c5943f)

**Comment by nozomione** [comment]
Merged #555
