### ISSUE TITLE
Hand-off: Multiplexed Project download options

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/scpca-portal#671]
### Context

For multiplexed projects users can now download:

- Only regular samples as SingleCellExperiment 
- Only regular samples as AnnData

### Problem or idea
The project  download modal should cover 3 cases:
- **Download multiplexed Project - All samples as SCE**
	- Merge option is disabled, an info line is presented below the option
	- The download summary has a warning that the download contains multiplexed samples
	- [Link to annotated mock-up](https://www.figma.com/file/zP12BqJhV4DgAhMUpJzF3Q/Untitled?type=whiteboard&node-id=1%3A227&t=qmjV8CvY01HntncO-1)
- **Download multiplexed Project - Exclude multiplex samples for SCE**
	- merge option is disabled, an info line is presented below the option
	- Download summary has an info saying multiplex samples are excluded
	- [Link to annotated mockup](https://www.figma.com/file/zP12BqJhV4DgAhMUpJzF3Q/Untitled?type=whiteboard&node-id=1%3A238&t=qmjV8CvY01HntncO-1)
- **Download multiplexed Project - AnnData**
	- merge option is disabled, an info line is presented below the option
	- exclude option is checked and disabled.
	- download summary has a warning saying multiplex samples are not available. 
	- [Link to annotated mockup](https://www.figma.com/file/zP12BqJhV4DgAhMUpJzF3Q/Untitled?type=whiteboard&node-id=1%3A321&t=qmjV8CvY01HntncO-1)

### Solution or next step

@davidsmejia let me know if you have any questions or if I missed something from our discussion.

**Comment by davidsmejia** [comment]
Looks like we want to display "Merged objects are not available for projects with multiplexed samples. Learn More" when merged objects are not available for any given project. We can add context aware text here but this would be a bit more brittle, because we would have to keep the API and the client in sync as to which condition. One of the benefits of pointing people to the docs here is that we dont have to do that sync.

We should probably consider putting a more generic message here such as:
> Merged objects are not available for every project. Learn more


pinging @dvenprasad for feedback

**Comment by dvenprasad** [comment]
Ah yes! yep, this sounds good to me!

**Comment by davidsmejia** [comment]
Closed with #676
